FROM node:18-alpine

# Установка необходимых зависимостей для sharp
RUN apk add --no-cache \
    vips-dev \
    gcc \
    g++ \
    make

# Установка рабочей директории
WORKDIR /app

# Копируем package.json и package-lock.json (если он есть)
COPY package*.json ./ 

# Устанавливаем зависимости
RUN npm install

# Копируем все файлы проекта в контейнер
COPY . .

# Выполняем сборку Strapi
RUN npm run build

# Открываем порты (по умолчанию Strapi использует 1337)
EXPOSE 1337

# Команда для запуска Strapi в режиме разработки 
CMD ["npm", "run", "dev"]
