FROM node:18-alpine

# Установка рабочей директории
WORKDIR /app

# Копируем package.json и package-lock.json (если он есть)
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем все файлы проекта в контейнер
COPY . .

# Выполняем сборку Strapi
RUN npm run build

# Открываем порты (по умолчанию Strapi использует 1337)
EXPOSE 1337

# Команда для запуска Strapi в режиме разработки 
# (запускаем в этом режиме потому что нам не нужно терять доступ к мутации коллекции данных)
CMD ["npm", "run", "dev"]
