FROM node:18.20-bullseye-slim

# Установка рабочей директории
WORKDIR /app

# Копируем package.json и package-lock.json (если он есть)
COPY package*.json ./ 

RUN rm -rf node_modules

# Устанавливаем зависимости и sharp для linuxmusl
RUN npm install

# RUN npm install --cpu=x64 --os=linux --libc=musl sharp

# Пересобираем sharp
# workaround: https://github.com/gatsbyjs/gatsby/issues/24559
# RUN npm rebuild --verbose sharp

# Копируем все файлы проекта в контейнер
COPY . .

# Выполняем сборку Strapi
RUN npm run build

# Открываем порты (по умолчанию Strapi использует 1337)
EXPOSE 1337

# Команда для запуска Strapi в режиме разработки 
CMD ["npm", "run", "dev"]
